[package]
name = "playground"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.5.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_derive = "1.0.192"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
warp = "0.3.6"
nemo-parser = { path = "../nemo-parser" }
nemo-backend = { path = "../nemo-backend" }
