[package]
name = "xtask-gen-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
proc-macro2 = "1.0.79"
quote = "1.0.36"
ungrammar = "1.16.1"
