[package]
name = "nemo-language-server"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
nemo-frontend = { path = "../nemo-frontend" }
lsp-server = "0.7.5"
lsp-types = "0.95.0"
serde = "1.0.192"
serde_json = "1.0.108"
tree-sitter-highlight = "0.22.2"
